### ISSUE TITLE
hi~ I have found a problem with the button

### ISSUE THREAD

**Issue by aa2246740** [bfeher/BFPaperButton#10]
I set the button isRase = FALSE
and my button was on a view which is smaller than screensize
I don't know why, everytime I hit it the first time it always have a ripple animate further than the bounce on the right....
I m using swift and the button is from storyboard. 
can you help:)

**Comment by bfeher** [comment]
Hi!

Sure, can you show me some code (if any) and maybe a screenshot of what's going on?

Thanks.

**Comment by aa2246740** [comment]
![img_5448](https://cloud.githubusercontent.com/assets/10174279/5703563/42d95d3a-9aa3-11e4-9810-b69d0f5f5313.PNG)
it's too hard for me to upload a photo...
I found out that I use Storyboard to create the button will have this problem 
but using code wont.
and it happens when u add the button in another viewcontroller and the button is from storyboard

**Comment by bfeher** [comment]
Hi,

Thanks for the screenshot. 

It seems like the button's frame extends beyond your white container view. This seems like either an issue with the Auto Layout code, or just with the view hierarchy. Is the button actually inside the white view or just on top of it?

Below is an example test I just made using the storyboard, no auto layout. I placed 3 buttons inside of a white view which sits on the main view (gray):

![screen shot 2015-01-13 at 09 19 07](https://cloud.githubusercontent.com/assets/3466708/5714024/6cafa05c-9b06-11e4-834b-9c0e5ab28857.png)


![bfpaperbuttontestgif](https://cloud.githubusercontent.com/assets/3466708/5714033/76538dda-9b06-11e4-9e69-79062f651511.gif)


Please check your layout and let me know if you have any more questions :)

**Comment by sean915213** [comment]
I also have this problem. Cannot upload teh codez.  plz help.

**Comment by aa2246740** [comment]
I use autolayout.. Oh here is how I recreate it 
I use a segue to present a new View 
inside it I put another white view inside 
I set this white view 4 constrains : top left right and height    i set top left right to 16 and height to 200
and i put a imageview inside and to the left dunno if this has to do with it cus in my project there is a imageview 
And now i put the bfpaperbutton right to the imageview
left top right height constrains again 
and this time u will see it ripples out of bound

**Comment by aa2246740** [comment]
Sorry I can't post picture...Its toooooo hard for me to post image from china..

**Comment by bfeher** [comment]
Try to set the background color of the button to something other than clear. Does the button's frame extend beyond the white view? It sounds like you aren't doing anything to prevent the frame of the button from extending beyond the white view. Did you set the button's right constraint to the edge of the white view?

This sounds like a typical Auto Layout issue and not a problem with the button itself.

**Comment by bfeher** [comment]
I imagine your layout like this:
____________
|                      |
|--[IV]--[BUTTON]
____________

It should be more like this:
____________
|                      |
|--[IV]--[BUT]--|
____________

**Comment by aa2246740** [comment]
I have the right constrain.. but it only bounce out of bound for the first time. and the sencond time you press it's normal again. 
all the button from that view is the same ..

**Comment by bfeher** [comment]
Hmm I'm really not sure. It would be helpful if you could paste your code.

If you look at `BFPaperButton.m` you will see in `growTapCircle`:

```ruby
// ...

CGRect endRect = CGRectMake(self.bounds.origin.x, self.bounds.origin.y , self.frame.size.width, self.frame.size.height);

// ...

// Setup background fade layer:
self.backgroundColorFadeLayer.frame = endRect;

// ...

mask.path = [UIBezierPath bezierPathWithRoundedRect:self.bounds cornerRadius:self.cornerRadius].CGPath;

// ...
```

That is how the fade layer and tap-circle clipping bounds are calculated.
I can't see anywhere where the bounds would be old or wrong after Auto Layout is run, since  `growTapCircle` is run on touch down.

If you pasted some code it may help us find the problem quicker.

Thanks!

PS: I'm not sure if this will do anything, but you may want to at least try changing the line of code:
```ruby
CGRect endRect = CGRectMake(self.bounds.origin.x, self.bounds.origin.y , self.frame.size.width, self.frame.size.height);
```
to 
```ruby
CGRect endRect = CGRectMake(self.bounds.origin.x, self.bounds.origin.y , self.bounds.size.width, self.bounds.size.height);
```

**Comment by bfeher** [comment]
oh! I was able to replicate your issue! I will let you know when I've fixed it!
Thanks!

**Comment by aa2246740** [comment]
thanks for ur work too!

**Comment by bfeher** [comment]
Hello!
I pushed version 1.6.1 which should fix this problem! Please let me know if it didn't work or if you find more bugs.

Thanks a lot!

**Comment by aa2246740** [comment]
it works perfectly now~!
