### ISSUE TITLE
Fast touch up inside

### ISSUE THREAD

**Issue by aekosyakov** [bfeher/BFPaperButton#12]
Hi,
Thank you for BFPaperButton, it looks great)
Could you help me some issue I got..
I am using BFPaperButtons inside UITableVIewCell,
when I push It fast, it stops and begins again not from correct state,
so it look like duplicate animation, pls see the gif file I attached.
And one more queation - is it possible not to "pause" animation
when you hold the button, but let it finish straight away?

thank u.

![bfpapaerbuttonissue](https://cloud.githubusercontent.com/assets/3143687/6318786/f4202fac-bab4-11e4-960a-cd99e25ecb85.gif)

**Comment by aekosyakov** [comment]
Ok, as I read in other closed issue it could be so because of delayContentTouches in tableview..
setting it to NO. but the result is the same.
Also I have a single BFPaperButton on a simle view in other vc, and it is working like a charm.
Seems like I should find the solution to fix up tableView's delayscontenttouches..

**Comment by bfeher** [comment]
Hi aekosyakov!

I'm not sure what is causing your issue but I would like to recommend that you use [BFPaperTableViewCell](https://github.com/bfeher/BFPaperTableViewCell) as the superclass of your cells! BFPaperTableViewCell was designed specifically for use within UITableViews and addresses content delays as well. If possible, you may want to try that instead.
