### ISSUE TITLE
only really notice effects on long press

### ISSUE THREAD

**Issue by hsavit1** [bfeher/BFPaperButton#16]
only on the first time I tap do I notice effects on a short press. Every other time needs to be a long press to observe effects. any reason why?

**Comment by bfeher** [comment]
Hi @hsavit1!

I'm having a hard time seeing this effect. Which version are you using and on which device? 
I'm testing with v2.0.18 on an iPad 4th gen running iOS 8.3 and I cannot see this effect.

**Comment by hsavit1** [comment]
I'm testing with the same version, and on iOS 8.3. My button is constrained
to edges with auto layout and has a mapview as a sub view, if that helps.

On Thursday, May 21, 2015, Bence Feher <notifications@github.com> wrote:

> Hi @hsavit1 <https://github.com/hsavit1>!
>
> I'm having a hard time seeing this effect. Which version are you using and
> on which device?
> I'm testing with v2.0.18 on an iPad 4th gen running iOS 8.3 and I cannot
> see this effect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bfeher/BFPaperButton/issues/16#issuecomment-104472272>
> .
>


-- 
Sent from Gmail Mobile

**Comment by bfeher** [comment]
The circles fade in until either the animation duration is reached or the tap has ended. At which point they burst and fade out. The animation values continue where they left off, so if you tap lightly the circle doesn't fade in very much and begins to fade out from its current alpha value.

I am not yet able to reproduce a more noticeable circle on the first tap. Perhaps the mapview is delaying the touch or interacting with it in some way? Autolayout should have no effect on the circle animations.

You may want to try using [BFPaperView](https://github.com/bfeher/BFPaperView) instead if you plan on adding complex subviews. Though I'm not sure if that will solve your issue.

**Comment by bfeher** [comment]
If you could upload a gif that would be helpful.

**Comment by hardikamal** [comment]
Hi @bfeher & @hsavit1 - Me too facing same problem...it requires long press to see the ripple effect...any solution found??

**Comment by bfeher** [comment]
Hi @hardikamal  - Have you read my previous comments? This may be the expected behavior. If you are using a mapview or some kind of complex subview in the button, I suggest using BFPaperView.

If you still believe this to be a bug I would really like some more information as well as some kind of evidence so I can better understand what's going on.

Thanks :)

**Comment by hardikamal** [comment]
Hi @bfeher & @hsavit1....by disabling delay content touches on scrollview/uitableview/uicollectionview we get click effect on without long longpress...Thanks solved

**Comment by bfeher** [comment]
Glad to hear that :)
