### ISSUE TITLE
How to use it with Storyboard?

### ISSUE THREAD

**Issue by terminatorlkf** [bfeher/BFPaperButton#22]
it really confused me that I don't know how to create a BFPaperButton using storyboard

**Comment by bfeher** [comment]
Hi @terminatorlkf !

Thank you for using this control :]
Below is a quick guide to getting started using BFPaperButton with Storyboards:

**1)** Drag and drop a **UIButton** onto a the Storyboard and change it's class to **BFPaperButton**:
![1](https://cloud.githubusercontent.com/assets/3466708/13972459/50a3b31c-f0dc-11e5-93de-e59842810a0c.png)

**2)** Change the button type to **Custom** _(optional, but recommended)_:
![2](https://cloud.githubusercontent.com/assets/3466708/13972472/7bb2f0ae-f0dc-11e5-997d-a69de9e8ad55.png)

**3.a)** Import 
`<UIColor+BFPaperColors/UIColor+BFPaperColors.h>` 
and `"BFPaperButton.h"   // or <BFPaperButton/BFPaperButton.h>`.
**3.b)** Drag and drop an **IBOutlet** into your ViewController for the button.
**3.c)** In `viewDidLoad` (or `viewWillAppear`, etc.) customize your BFPaperButton!
![3](https://cloud.githubusercontent.com/assets/3466708/13972539/f729589a-f0dc-11e5-946a-256bdbde4a66.png)

**Result:**
![4](https://cloud.githubusercontent.com/assets/3466708/13972544/ff770790-f0dc-11e5-848d-0398bf0be5bb.png)



Let me know if you have anymore questions. Thanks!

**Comment by terminatorlkf** [comment]
thanks！I sincerely appreciate your help

发自我的 iPhone
