### ISSUE TITLE
Animations can't play when Buttons in UIScrollView

### ISSUE THREAD

**Issue by heiyeliuying** [bfeher/BFPaperButton#23]
Dear author: I just add the buttons in  my UIScrollView . the question is I can receive the click method ,but the animation can't play without a  long press . can you help me ?

**Comment by bfeher** [comment]
Hi @heiyeliuying !
Have you tried setting the UIScrollView's property: `delaysContentTouches = NO`?

**Comment by heiyeliuying** [comment]
Thanks a lot , it work now !

**Comment by bfeher** [comment]
Happy to help :]
