### ISSUE TITLE
Run is not smooth

### ISSUE THREAD

**Issue by xiaopn166** [bfeher/BFPaperButton#24]
OC Code:
In a ViewController , the code >> [self.view addSubView:BFPaperButton ] , it is run normal and smooth. 
I have a problem , In my ViewController has a UIScrollView , and some UIView in the UIScrollView , and put a BFPaperButton in the UIView. Run app and click the BFPaperButton ,it is not smooth.

**Comment by bfeher** [comment]
Hi @xiaopn166 
Have you tried setting the UIScrollView's property: `delaysContentTouches = NO`?

**Comment by xiaopn166** [comment]
@bfeher I haven't. I tried your way . The "delaysContentTouches = NO" can solve my problem.Thanks.

**Comment by bfeher** [comment]
Glad to help :)
