### ISSUE TITLE
You have this bug

### ISSUE THREAD

**Issue by wutao66** [bfeher/BFPaperButton#27]
hi，You have this bug，Your self.layer did not clear

**Comment by bfeher** [comment]
Hi @wutao66 ! Could you be more specific? Where does this happen? Under what circumstances? Can you show me?

Thanks!

**Comment by wutao66** [comment]
You first set a button in the main interface, click on the other interface，this interface Add to you BFPaperButton,this btn Background color is set to black，You can set a few more it,You repeatedly Click it,Then return to half slip，look this BFPaperButton，you will see

**Comment by bfeher** [comment]
Hi @wutao66 !

Thanks for the feedback! I'm having a hard time understanding how to replicate this bug. Can you make some screenshots or an animated gif capturing the bug?

Thank you.

**Comment by wutao66** [comment]
hi,@bfeher 
[Uploading lala.gif.zip…]()

**Comment by wutao66** [comment]
hi,@bfeher
