### ISSUE TITLE
layoutSubviews ignores enabled property

### ISSUE THREAD

**Issue by ujikol** [bfeher/BFPaperButton#28]
layoutSubviews ignores the enabled property, hence resets the appearance of the button to enabled while it may actually be and work as enabled.

My simple but dirty workaround is the following:
```
extension BFPaperButton {
	override public func layoutSubviews() {
		super.layoutSubviews()
		self.enabled = self.enabled
	}
}

```

**Comment by bfeher** [comment]
Hi @ujikol !

Thank you for pointing this out to me! I believe I just fixed it and released a new version, 2.1.1.

Please let me know if the bug still persists after updating :)

Thanks!
