### ISSUE TITLE
Get rid of dots

### ISSUE THREAD

**Issue by rahulbbit** [bfeher/BFPaperButton#33]
Recently been facing this issue. Whenever i click on the button a dot shows up. like the second button in the GIF

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/11924067/32713679-610dcc98-c870-11e7-82ef-8116656c46cb.gif)

**Comment by bfeher** [comment]
Hi @rahulbbit! Could you please tell me what OS and device/simulator you are using?
I can't seem to reproduce this bug while using Xcode 9.1 (9B55) and iOS 11 on any simulator device.
Thanks!

**Comment by rahulbbit** [comment]
It magically disappeared. I just restarted XCODE

**Comment by bfeher** [comment]
Thanks I hope that will be the end of them and they won't come back :)
